[Service]
  Host = "192.168.3.178"
  Port = 49997
  ConnectRetries = 3
  Labels = []
  OpenMsg = "device opcua golang started"
  Timeout = 5000
  EnableAsyncReadings = true
  AsyncBufferSize = 16

[Registry]
  Host = "192.168.3.130"
  Port = 8500
  CheckInterval = "10s"
  FailLimit = 3
  FailWaitTime = 10
  Type = "consul"

[Clients]
  [Clients.Data]
    Name = "edgex-core-data"
    Protocol = "http"
    Host = "192.168.3.130"
    Port = 48080
    Timeout = 5000

  [Clients.Metadata]
    Name = "edgex-core-metadata"
    Protocol = "http"
    Host = "192.168.3.130"
    Port = 48081
    Timeout = 5000

  [Clients.Logging]
    Name = "edgex-support-logging"
    Protocol = "http"
    Host = "192.168.3.130"
    Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 12800
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

[Logging]
  EnableRemote = false
  File = "./device-opcua.log"

[Writable]
  LogLevel = "INFO"

# Pre-define Devices
[[DeviceList]]
  Name = "t"
  Profile = "OPCUA-Server-t"
  Description = "OPCUA device is created for test purpose"
  Labels = [ "test" ]
  [DeviceList.Protocols]
      [DeviceList.Protocols.opcua]
#         Endpoint = "opc.tcp://192.168.3.165:53530/OPCUA/SimulationServer"
          Protocol = "opc.tcp"
          Address = "192.168.3.165"
          Port = "53530"
          Path = "/OPCUA/SimulationServer"
          MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"
          Policy = "None"
          Mode = "None"
          CertFile = ""
          KeyFile = ""
