[Service]
  Host = "192.168.3.177"
  Port = 49997
  ConnectRetries = 3
  Labels = []
  OpenMsg = "device opcua golang started"
  Timeout = 5000
  EnableAsyncReadings = true
  AsyncBufferSize = 16

[Registry]
  Host = "192.168.3.130"
  Port = 8500
  CheckInterval = "10s"
  FailLimit = 3
  FailWaitTime = 10
  Type = "consul"

[Clients]
  [Clients.Data]
    Name = "edgex-core-data"
    Protocol = "http"
    Host = "192.168.3.130"
    Port = 48080
    Timeout = 5000

  [Clients.Metadata]
    Name = "edgex-core-metadata"
    Protocol = "http"
    Host = "192.168.3.130"
    Port = 48081
    Timeout = 5000

  [Clients.Logging]
    Name = "edgex-support-logging"
    Protocol = "http"
    Host = "192.168.3.130"
    Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 12800
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

[Logging]
  EnableRemote = false
  File = "./device-opcua.log"

[Writable]
  LogLevel = "INFO"

# Pre-define Devices
[[DeviceList]]
  Name = "SimulationServer"
  Profile = "OPCUA-Server"
  Description = "OPCUA device is created for test purpose"
  [DeviceList.Protocols]
      [DeviceList.Protocols.opcua]
#          Protocol = "opc.tcp"
          Address = "192.168.3.165"
          Port = "53530"
          Path = "/OPCUA/SimulationServer"
          MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"
#          Policy = "None"
#          Mode = "None"
#          CertFile = ""
#          KeyFile = ""

[[DeviceList]]
  Name = "Vibrator01"
  Profile = "VibrationSensorDoc"
  Description = "Vibrator for test at 192.168.3.188"
  Labels = [ "VibrationSensor" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.188"
      Port = "4840"
      MappingStr = "{ \"Vibration\": \"ns=1;i=115\", \"Switch\": \"ns=1;i=116\" }"

################## 20 devices ###########################################################
[[DeviceList]]
  Name = "SimulationServer01"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer02"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer03"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer04"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer05"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer06"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer07"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer08"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer09"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer10"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer11"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer12"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer13"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer14"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer15"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer16"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer17"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer18"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer19"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"

[[DeviceList]]
  Name = "SimulationServer20"
  Profile = "OPCUA-Server"
  [DeviceList.Protocols]
    [DeviceList.Protocols.opcua]
      Address = "192.168.3.165"
      Port = "53530"
      Path = "/OPCUA/SimulationServer"
      MappingStr = "{ \"Counter\": \"ns=5;s=Counter1\", \"Random\": \"ns=5;s=Random1\" }"


#########################################################################################